name: Fake Deploy
on:
  workflow_call:
jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no ambiente
        run: echo "Executando o deploy no ambiente de desenvolvimento"