name: CI/CD Fake
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: dev
        required: true
        description: Environment of deployment
        options:
          - dev
          - test
          - staging
          - prod
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Imagem Docker
        run: echo "Execução do comando de docker build"
      - name: Execução de Testes de Software
        run: echo "Aqui eu executo o teste de software"
      - name: Publicando a Release
        run: echo "Publicação da Relase final"
  CD:
    needs: [CI]
    uses: Curso-Devops-Pro-2025/reaproveitamento-workflow/.github/workflows/cd.yaml@master
    with:
      environment: ${{ inputs.environment }}